CREATE LOGIN [autsalud_webusr]
    WITH PASSWORD = N'{WHPtsInRhSfdXkF|rof,c{smsFT7_&#$!~<jSfNwho{c|Rh', SID = 0x27E9CEB6DD9A0D429A1222328DDED71F, DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

