CREATE TABLE [dbo].[tbHistoricoTarificacionXReliquidacion] (
    [cnsctvo_hstrco_prcso_lqdcn] INT                IDENTITY (1, 1) NOT NULL,
    [nmro_unco_idntfccn]         INT                NULL,
    [edd_bnfcro]                 INT                NULL,
    [cnsctvo_cdgo_pln]           INT                NULL,
    [ps_ss]                      VARCHAR (1)        NULL,
    [fcha_aflcn_pc]              DATETIME           NULL,
    [cnsctvo_cdgo_prntsco]       INT                NULL,
    [cnsctvo_cdgo_tpo_afldo]     INT                NULL,
    [dscpctdo]                   VARCHAR (1)        NULL,
    [estdnte]                    VARCHAR (1)        NULL,
    [antgdd_hcu]                 VARCHAR (1)        NULL,
    [atrzdo_sn_Ps]               VARCHAR (1)        NULL,
    [grpo_bsco]                  VARCHAR (1)        NULL,
    [cnsctvo_cdgo_tpo_cntrto]    INT                NULL,
    [nmro_cntrto]                CHAR (15)          NULL,
    [cnsctvo_bnfcro]             INT                NULL,
    [cnsctvo_cbrnza]             INT                NULL,
    [grpo]                       INT                NULL,
    [cnsctvo_prdcto]             INT                NULL,
    [cnsctvo_mdlo]               INT                NULL,
    [vlr_upc]                    INT                NULL,
    [vlr_rl_pgo]                 INT                NULL,
    [cnsctvo_cdgo_tps_cbro]      INT                NULL,
    [cbrnz_cn_prdcto]            INT                NULL,
    [bnfcr_cn_prdcto]            INT                NULL,
    [cn_mdlo]                    INT                NULL,
    [grpo_trfccn]                INT                NULL,
    [igl_pln]                    INT                NULL,
    [grpo_mdlo]                  INT                NULL,
    [nmro_unco_idntfccn_empldr]  INT                NULL,
    [cnsctvo_scrsl]              INT                NULL,
    [cnsctvo_cdgo_clse_aprtnte]  INT                NULL,
    [cnsctvo_cdgo_lqdcn]         INT                NULL,
    [inco_vgnca_cntrto]          DATETIME           NULL,
    [fcha_incl_prdo_lqdcn]       DATETIME           NULL,
    [bnfcdo_pc]                  CHAR (1)           NULL,
    [fcha_crcn]                  DATETIME           NULL,
    [usro_crcn]                  [dbo].[udtUsuario] NULL,
    [tmp_stmp]                   ROWVERSION         NULL,
    CONSTRAINT [PK_tbHistoricoTarificacionXReliquidacion] PRIMARY KEY CLUSTERED ([cnsctvo_hstrco_prcso_lqdcn] ASC),
    CONSTRAINT [FK_tbHistoricoTarificacionXReliquidacion_tbLiquidaciones] FOREIGN KEY ([cnsctvo_cdgo_lqdcn]) REFERENCES [dbo].[tbLiquidaciones] ([cnsctvo_cdgo_lqdcn])
);

