CREATE TABLE [dbo].[TPagos] (
    [cnsctvo_cdgo_pgo]          [dbo].[udtConsecutivo]          NULL,
    [nmro_dcmnto]               [dbo].[udtNumeroFormulario]     NULL,
    [vlr_dcmnto]                [dbo].[udtValorGrande]          NULL,
    [nmro_unco_idntfccn_empldr] [dbo].[udtConsecutivo]          NULL,
    [cnsctvo_scrsl]             [dbo].[udtConsecutivo]          NULL,
    [cnsctvo_cdgo_clse_aprtnte] [dbo].[udtConsecutivo]          NULL,
    [fcha_rcdo]                 DATETIME                        NULL,
    [fcha_aplcn]                DATETIME                        NULL,
    [nmro_rmsa]                 INT                             NULL,
    [nmro_lna]                  INT                             NULL,
    [cnsctvo_cdgo_estdo_pgo]    [dbo].[udtConsecutivo]          NULL,
    [cnsctvo_cdgo_tpo_pgo]      [dbo].[udtConsecutivo]          NULL,
    [usro_crcn]                 [dbo].[udtUsuario]              NULL,
    [sldo_pgo]                  [dbo].[udtValorGrande]          NULL,
    [dscrpcn_estdo_pgo]         [dbo].[udtDescripcion]          NULL,
    [dscrpcn_tpo_pgo]           [dbo].[udtDescripcion]          NULL,
    [nmbre_scrsl]               VARCHAR (200)                   NULL,
    [nmro_idntfccn]             [dbo].[udtNumeroIdentificacion] NULL,
    [cdgo_tpo_idntfccn]         [dbo].[udtTipoIdentificacion]   NULL,
    [dscrpcn_clse_aprtnte]      VARCHAR (30)                    NULL,
    [rzn_scl]                   VARCHAR (200)                   NULL,
    [cnsctvo_cdgo_tpo_idntfccn] INT                             NULL,
    [dgto_vrfccn]               INT                             NULL,
    [cnsctvo_prcso]             INT                             NULL,
    [fcha_fn_prcso]             DATETIME                        NULL,
    [vlr_ants_iva]              INT                             NULL,
    [vlr_iva]                   INT                             NULL
);

