CREATE TABLE [dbo].[tbCafam] (
    [tpo_idntfccn_bnfcro]       CHAR (1)  NOT NULL,
    [nmro_idntfccn_bnfcro]      CHAR (12) NOT NULL,
    [fcha_dsde]                 DATETIME  NOT NULL,
    [fcha_hsta]                 DATETIME  NOT NULL,
    [nmro_idntfccn_ctznte]      CHAR (12) NOT NULL,
    [prmr_aplldo_bnfcro]        CHAR (15) NOT NULL,
    [sgndo_aplldo_bnfcro]       CHAR (15) NULL,
    [nmbrs_bnfcro]              CHAR (15) NOT NULL,
    [fcha_ncmnto]               CHAR (10) NOT NULL,
    [tpo_afldo]                 CHAR (1)  NOT NULL,
    [drccn]                     CHAR (45) NOT NULL,
    [cdgo_cdd]                  CHAR (5)  NULL,
    [cdgo_dprtmnto]             CHAR (2)  NOT NULL,
    [tlfno]                     CHAR (15) NULL,
    [sxo]                       CHAR (1)  NOT NULL,
    [espacio1]                  CHAR (4)  NULL,
    [inco_vgnca]                CHAR (10) NOT NULL,
    [prevision]                 CHAR (1)  NULL,
    [espacio2]                  CHAR (2)  NULL,
    [rngo_slrl]                 CHAR (1)  NULL,
    [convenio]                  CHAR (2)  NOT NULL,
    [cantidad_ben]              CHAR (3)  NOT NULL,
    [niteps]                    CHAR (9)  NOT NULL,
    [estdo]                     CHAR (1)  NOT NULL,
    [smns_ctzds]                CHAR (4)  NULL,
    [tpo_nvdd]                  CHAR (1)  NOT NULL,
    [nmro_unco_idntfccn_bnfcro] INT       NULL,
    [nmro_unco_idntfccn_ctznte] INT       NULL,
    [cnsctvo_cdgo_tpo_afldo]    INT       NULL,
    [cnsctvo_cdgo_rngo_slrl]    INT       NULL,
    [cnsctvo_cdgo_cdd]          INT       NULL,
    [cnsctvo_cdgo_sxo]          INT       NULL,
    [cnsctvo_cdgo_tpo_idntfccn] INT       NULL,
    [fcha_gnrcn]                DATETIME  NULL,
    [usro_gnrcn]                CHAR (30) NULL,
    [mqna_gnrcn]                CHAR (30) NULL,
    [sgndo_nmbre]               CHAR (15) NOT NULL,
    [tpo_idntfccn_ctznte]       CHAR (1)  NOT NULL,
    [cnsctvo_cdgo_prntsco]      INT       NULL,
    [tpo_prntsco]               CHAR (2)  NULL
);

