CREATE TABLE [dbo].[tbPersonas] (
    [nmro_unco_idntfccn]          INT           NOT NULL,
    [prmr_aplldo]                 CHAR (50)     NOT NULL,
    [sgndo_aplldo]                CHAR (50)     NOT NULL,
    [prmr_nmbre]                  CHAR (30)     NOT NULL,
    [sgndo_nmbre]                 CHAR (30)     NOT NULL,
    [tlfno_rsdnca]                CHAR (30)     NOT NULL,
    [drccn_rsdnca]                VARCHAR (80)  NOT NULL,
    [cnsctvo_cdgo_cdd_rsdnca]     INT           NOT NULL,
    [eml]                         VARCHAR (50)  NOT NULL,
    [cnsctvo_cdgo_lgr_crrspndnca] INT           NOT NULL,
    [cnsctvo_cdgo_cdd_crrspndnca] INT           NOT NULL,
    [drccn_crrspndnca]            VARCHAR (80)  NOT NULL,
    [cnsctvo_cdgo_sxo]            INT           NOT NULL,
    [cnsctvo_cdgo_estdo_cvl]      INT           NOT NULL,
    [cnsctvo_ultmo_ano_aprbdo]    INT           NOT NULL,
    [cnsctvo_cdgo_grdo_esclr]     INT           NOT NULL,
    [fcha_ncmnto]                 DATETIME      NOT NULL,
    [cnsctvo_cdgo_brro]           INT           NOT NULL,
    [nmbre_lcldd]                 VARCHAR (150) NOT NULL,
    [estdo_vtl]                   CHAR (1)      NOT NULL,
    [cnsctvo_cdgo_estrto_sccnmco] INT           NOT NULL,
    [tlfno_crrspndnca]            CHAR (30)     NOT NULL,
    [fcha_actlzcn_rgstro]         DATETIME      NOT NULL,
    [tme_stmp]                    ROWVERSION    NOT NULL,
    [tlfno_adcnl]                 CHAR (30)     NULL,
    [tlfno_cllr]                  CHAR (30)     NULL,
    [cnsctvo_cdgo_csa_mvldd]      INT           NOT NULL,
    [cnsctvo_cdgo_etna]           INT           NULL
);

