CREATE TABLE [dbo].[tmp_cafam] (
    [nmro_idntfccn_bnfcro] CHAR (12) NULL,
    [nmro_idntfccn_ctznte] CHAR (12) NULL,
    [tpo_idntfccn_bnfcro]  CHAR (1)  NULL,
    [prmr_aplldo_bnfcro]   CHAR (15) NULL,
    [sgndo_aplldo_bnfcro]  CHAR (15) NULL,
    [nmbrs_bnfcro]         CHAR (30) NULL,
    [fcha_ncmnto]          CHAR (10) NULL,
    [tpo_afldo]            CHAR (1)  NULL,
    [drccn]                CHAR (45) NULL,
    [cdgo_cdd]             CHAR (5)  NULL,
    [cdgo_dprtmnto]        CHAR (2)  NULL,
    [tlfno]                CHAR (15) NULL,
    [sxo]                  CHAR (1)  NULL,
    [espacio1]             CHAR (4)  NULL,
    [inco_vgnca]           CHAR (10) NULL,
    [prevision]            CHAR (1)  NULL,
    [espacio2]             CHAR (2)  NULL,
    [rngo_slrl]            CHAR (1)  NULL,
    [convenio]             CHAR (2)  NULL,
    [cantidad_ben]         CHAR (3)  NULL,
    [niteps]               CHAR (9)  NULL,
    [estdo]                CHAR (1)  NULL,
    [smns_ctzds]           CHAR (4)  NULL,
    [tpo_nvdd]             CHAR (1)  NULL,
    [rgstro]               INT       NULL,
    [sgndo_nmbre]          CHAR (15) NULL,
    [tpo_idntfccn_ctznte]  CHAR (1)  NULL,
    [fcha_gnrcn]           CHAR (10) NULL,
    [tpo_prntsco]          CHAR (2)  NULL
);

