CREATE TABLE [dbo].[tmpResultadoPACFE] (
    [nmbre_scrsl]         VARCHAR (200)                        NULL,
    [drccn]               VARCHAR (80)                         NULL,
    [cnsctvo_scrsl]       VARCHAR (16)                         NOT NULL,
    [tlfno]               VARCHAR (34)                         NOT NULL,
    [dscrpcn_cdd]         VARCHAR (100)                        NULL,
    [cdgo_sde]            VARCHAR (4)                          NULL,
    [fcha_incl_fctrcn]    VARCHAR (29)                         NOT NULL,
    [nmro_estdo_cnta]     VARCHAR (15)                         NULL,
    [Cts_sn_Cnclr]        INT                                  NULL,
    [Cts_Cnclr]           INT                                  NULL,
    [fechaPago]           VARCHAR (23)                         NULL,
    [cdgo_tpo_idntfccn]   VARCHAR (3)                          NULL,
    [ttl_fctrdo]          NUMERIC (12)                         NULL,
    [vlr_iva]             NUMERIC (12)                         NULL,
    [sldo_antrr]          NUMERIC (12)                         NULL,
    [sldo_fvr]            NUMERIC (12)                         NULL,
    [ttl_pgr]             NUMERIC (12)                         NULL,
    [mensaje]             NVARCHAR (1000)                      NULL,
    [mensaje2]            NVARCHAR (1000)                      NULL,
    [codigo_barras]       VARCHAR (500)                        NULL,
    [identificacion]      VARCHAR (24)                         NOT NULL,
    [cuenta_bancaria]     VARCHAR (200)                        NULL,
    [revisoria]           VARCHAR (200)                        NULL,
    [direccionSOS]        VARCHAR (200)                        NULL,
    [pbxSOS]              VARCHAR (15)                         NULL,
    [faxSOS]              VARCHAR (1)                          NOT NULL,
    [extensionSOS]        VARCHAR (1)                          NOT NULL,
    [lineaAtencionSOS]    VARCHAR (20)                         NULL,
    [nmro_idntfccn]       [dbo].[udtNumeroIdentificacionLargo] NULL,
    [Valor_Codigo_barras] VARCHAR (500)                        NULL,
    [fechaExpedicion]     VARCHAR (10)                         NULL,
    [cufe]                VARCHAR (160)                        NULL,
    [cadenaQR]            VARCHAR (2000)                       NULL,
    [totalPagarLetras]    VARCHAR (250)                        NULL,
    [nmro_unco_idntfccn]  [dbo].[udtConsecutivo]               NULL,
    [id]                  INT                                  NULL
);

